# Generated by Django 5.0.6 on 2024-06-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empID', models.IntegerField(primary_key=True)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField()),
                ('dept', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('add', models.CharField(max_length=100)),
                ('sal', models.IntegerField()),
            ],
        ),
    ]
